id:193
user_name:think.ccf.org
user_id:10.66.101.117-164bbe130b6d4e5f
script:PD Test
start_time:1547657217849
command:su -c ./pd_test.py -s /bin/sh vishhvaan
exit_code:1
>>>>>  OUTPUT STARTED <<<<<
Traceback (most recent call last):
  File "./pd_test.py", line 19, in <module>
    GPIO.setup(P_LED_pins, GPIO.OUT)
RuntimeError: No access to /dev/mem.  Try running as root!
