id:185
user_name:lri-107674.ccf.org
user_id:10.66.100.211-4b004016d50641d3
script:PD Test
start_time:1547425652073
command:su -c ./pd_test.py -s /bin/sh vishhvaan
exit_code:1
>>>>>  OUTPUT STARTED <<<<<
Traceback (most recent call last):
  File "./pd_test.py", line 19, in <module>
    GPIO.setup(P_LED_pins, GPIO.OUT)
RuntimeError: No access to /dev/mem.  Try running as root!
