id:275
user_name:172.26.40.155
user_id:172.26.40.1-fd619819a3174031
script:Pumps and LED Off
start_time:1552835837880
command:su -c ./pumpsledoff.py -s /bin/sh vishhvaan
exit_code:0
>>>>>  OUTPUT STARTED <<<<<
EVEs Enabled:
[1, 2, 3]
Started
Pin Lists:
Process Process-1:
Process Process-2:
Process Process-3:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "./pumpsledoff.py", line 42, in runner
    pipins = config[confsec].getboolean('Pi_pins')
  File "./pumpsledoff.py", line 42, in runner
    pipins = config[confsec].getboolean('Pi_pins')
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/configparser.py", line 956, in __getitem__
    raise KeyError(key)
  File "/usr/lib/python3.5/configparser.py", line 956, in __getitem__
    raise KeyError(key)
  File "./pumpsledoff.py", line 42, in runner
    pipins = config[confsec].getboolean('Pi_pins')
  File "/usr/lib/python3.5/configparser.py", line 956, in __getitem__
    raise KeyError(key)
KeyError: "EVE<module 'sys' (built-in)>"
KeyError: "EVE<module 'sys' (built-in)>"
KeyError: "EVE<module 'sys' (built-in)>"
